# Generated by Django 6.0.3 on 2026-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_remove_contact_email_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='big_fan',
            field=models.BooleanField(default=False),
        ),
    ]
