# Generated by Django 6.0.3 on 2026-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_contact_big_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
